config/routes.rb
RpgMin::Application.routes.draw do
  post 'attack' => 'home#attack', as: :attack
  get 'fixed_attack' => 'home#fixed_attack', as: :fixed_attack

  root 'home#index'

end

app/models/arco.rb
class Arco

  def usar
    "acertado en el corazón del enemigo"
  end
end

app/models/elfo.rb
class Elfo
  attr_accessor :item

  def initialize(item)
    @item = item
  end

  def atacar
    "Legolas ha #{@item.usar}"
  end
end

app/models/espada.rb
class Espada

  def usar
    "partido en dos a su enemigo"
  end
end

app/models/hechizo.rb
class Hechizo

  def usar
    "convertido en mono al enemigo"
  end
end

app/models/mago.rb
class Mago
  attr_accessor :item

  def initialize(item)
    @item = item
  end

  def atacar
    "Merlin ha #{item.usar}"
  end
end

app/models/paladin.rb
class Paladin
  attr_accessor :item

  def initialize(item)
    @item = item
  end

  def atacar
    "Conan ha #{@item.usar}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @personajes = [['Paladín','Paladin'],'Elfo','Mago']
    @armas = ['Espada','Arco','Hechizo']

    @instance_personaje = nil
  end

  def attack
    @personajes = [['Paladín','Paladin'],'Elfo','Mago']
    @armas = ['Espada','Arco','Hechizo']

    arma = Object.const_get(params[:arma])
    personaje = Object.const_get(params[:personaje])

    @instance_personaje = personaje.new(arma.new)
    logger.debug @instance_personaje.atacar

    render :index 
  end

  def fixed_attack
    @personajes = [['Paladín','Paladin'],'Elfo','Mago']
    @armas = ['Espada','Arco','Hechizo']

    @personaje = Paladin.new(Espada.new)

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Home#index

.row-fluid
  .span6
    %h2 Personaje Fijo
    
    %ul
      %li Paladin
      %li Espada

    = link_to t('.attack',default:'Attack!'), fixed_attack_path, class: 'btn btn-large'

    - unless @personaje.nil?
      %strong
        = @personaje.atacar

  .span6
    %h2 Personaje Dinámico

    = form_tag attack_path do
      = label_tag :personaje
      = select_tag :personaje,options_for_select(@personajes)

      = label_tag :arma
      = select_tag :arma,options_for_select(@armas)

      .form-actions
        = submit_tag t('.attack',default:'Attack!'), class: 'btn btn-large'

    - unless @instance_personaje.nil?
      %strong
        = @instance_personaje.atacar

= debug(@instance_personaje)

%p Find me in app/views/home/index.html.haml

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 2.3
.navbar
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .nav-collapse.collapse
        .navbar.navbar-fixed-top
          %nav.navbar-inner
            %ul.nav
              = link_to 'Home', root_path, class: 'brand'
              = render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Rpg Min'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Rpg Min'}"}
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    -# application layout styled for Bootstrap 2.3
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container-fluid
        = render 'layouts/messages'
        = yield
    %footer